package pl.dubba.share.protocol

import org.json.JSONObject
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

/**
 * Verifies the Kotlin marshaller produces byte-identical output to the Go
 * reference. Vectors are generated by `server/cmd/vectordump` and live in
 * src/test/resources/testvectors.json. Regenerate after any wire-format change:
 *   cd server && go run ./cmd/vectordump > ../client/Android/protocol/src/test/resources/testvectors.json
 */
class VectorsTest {
    private val v = JSONObject(
        VectorsTest::class.java.getResourceAsStream("/testvectors.json")!!
            .bufferedReader().use { it.readText() }
    )

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { ((s[it * 2].digitToInt(16) shl 4) or s[it * 2 + 1].digitToInt(16)).toByte() }

    private fun u64(s: String): Long = java.lang.Long.parseUnsignedLong(s, 16)

    @Test
    fun abstractFrames() {
        val arr = v.getJSONArray("abstractFrame")
        for (i in 0 until arr.length()) {
            val o = arr.getJSONObject(i)
            val expected = hex(o.getString("expectedHex"))
            val f = AbstractFrame(u64(o.getString("connIdHex")), o.getInt("frameType"), hex(o.getString("bodyHex")))
            assertContentEquals(expected, Marshaller.marshalAbstractFrame(f), "marshal abstractFrame[$i]")

            val back = Marshaller.unmarshalAbstractFrame(expected)
            assertNotNull(back, "unmarshal abstractFrame[$i]")
            assertEquals(f.connId, back.connId, "connId[$i]")
            assertEquals(f.frameType, back.frameType, "frameType[$i]")
            assertContentEquals(f.body, back.body, "body[$i]")
        }
    }

    @Test
    fun handshakeClient() {
        val o = v.getJSONArray("handshakeClient").getJSONObject(0)
        val expected = hex(o.getString("expectedHex"))
        val f = ClientHandshakeFrame(hex(o.getString("ecdhHex")), o.getInt("protoVersion"))
        assertContentEquals(expected, Marshaller.marshalHandshakeClient(f))

        val back = Marshaller.unmarshalHandshakeClient(expected)
        assertNotNull(back)
        assertContentEquals(f.ecdh, back.ecdh)
        assertEquals(f.protoVersion, back.protoVersion)
    }

    @Test
    fun handshakeServer() {
        val o = v.getJSONArray("handshakeServer").getJSONObject(0)
        val expected = hex(o.getString("expectedHex"))
        val f = ServerHandshakeFrame(
            ecdh = hex(o.getString("ecdhHex")),
            signature = hex(o.getString("signatureHex")),
            status = o.getInt("status"),
            connectionId = u64(o.getString("connectionIdHex")),
        )
        assertContentEquals(expected, Marshaller.marshalHandshakeServer(f))

        val back = Marshaller.unmarshalHandshakeServer(expected)
        assertNotNull(back)
        assertContentEquals(f.ecdh, back.ecdh)
        assertContentEquals(f.signature, back.signature)
        assertEquals(f.status, back.status)
        assertEquals(f.connectionId, back.connectionId)
    }

    @Test
    fun encryptedFrames() {
        val key = hex(v.getString("keyHex"))
        val e = v.getJSONObject("encrypted")

        e.getJSONObject("encryptedHandshakeClient").let { o ->
            assertContentEquals(
                hex(o.getString("expectedHex")),
                Marshaller.marshalEncryptedHandshakeClient(
                    EncryptedClientHandshakeFrame(o.getLong("featFlag")), key, o.getLong("counter")
                ),
                "encryptedHandshakeClient",
            )
        }

        e.getJSONObject("encryptedHandshakeServer").let { o ->
            assertContentEquals(
                hex(o.getString("expectedHex")),
                Marshaller.marshalEncryptedHandshakeServer(
                    EncryptedServerHandshakeFrame(o.getLong("featFlag"), hex(o.getString("aliasHex"))),
                    key, o.getLong("counter"),
                ),
                "encryptedHandshakeServer",
            )
        }

        e.getJSONObject("ping").let { o ->
            val expected = hex(o.getString("expectedHex"))
            assertContentEquals(
                expected,
                Marshaller.marshalPing(PingFrame(o.getInt("nonce")), key, o.getLong("counter")),
                "ping",
            )
            val back = Marshaller.unmarshalPing(expected, key)
            assertNotNull(back, "ping round-trip decrypt")
            assertEquals(o.getInt("nonce"), back.nonce)
        }

        e.getJSONObject("data").let { o ->
            assertContentEquals(
                hex(o.getString("expectedHex")),
                Marshaller.marshalData(DataFrame(hex(o.getString("dataHex"))), key, o.getLong("counter")),
                "data",
            )
        }

        e.getJSONObject("ctrl").let { o ->
            assertContentEquals(
                hex(o.getString("expectedHex")),
                Marshaller.marshalCtrl(
                    CtrlFrame(o.getInt("ctrlType"), o.getInt("ctrlNonce"), hex(o.getString("extraHex"))),
                    key, o.getLong("counter"),
                ),
                "ctrl",
            )
        }
    }

    @Test
    fun kdf() {
        val o = v.getJSONArray("kdf").getJSONObject(0)
        val keys = Crypto.deriveKeys(
            hex(o.getString("sharedSecretHex")),
            u64(o.getString("serverConnIdHex")),
            u64(o.getString("clientConnIdHex")),
        )
        assertContentEquals(hex(o.getString("k1Hex")), keys.k1, "kdf k1")
        assertContentEquals(hex(o.getString("k2Hex")), keys.k2, "kdf k2")
    }

    @Test
    fun ecdhEndToEnd() {
        val o = v.getJSONArray("ecdh").getJSONObject(0)
        val serverPub = hex(o.getString("serverPubHex"))
        val clientPub = hex(o.getString("clientPubHex"))

        // pubkey decode -> re-encode reproduces Go's 65-byte wire format
        assertContentEquals(serverPub, Crypto.encodePublicKey(Crypto.decodePublicKey(serverPub)), "server pub round-trip")
        assertContentEquals(clientPub, Crypto.encodePublicKey(Crypto.decodePublicKey(clientPub)), "client pub round-trip")

        // ECDH(serverPriv, clientPub) reproduces Go's shared secret
        val serverPriv = Crypto.privateKeyFromScalar(hex(o.getString("serverScalarHex")))
        val shared = Crypto.ecdh(serverPriv, Crypto.decodePublicKey(clientPub))
        assertContentEquals(hex(o.getString("sharedHex")), shared, "ecdh shared secret")

        val keys = Crypto.deriveKeys(shared, u64(o.getString("serverConnIdHex")), u64(o.getString("clientConnIdHex")))
        assertContentEquals(hex(o.getString("k1Hex")), keys.k1, "ecdh k1")
        assertContentEquals(hex(o.getString("k2Hex")), keys.k2, "ecdh k2")
    }
}
