package pl.dubba.share.net

import android.content.Context
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import pl.dubba.share.log.DebugLog

/**
 * Singleton state shared between the foreground service (writer) and the
 * Activity (reader). Lives as long as the process. The service is the only
 * writer; the Activity reads via StateFlow.collectAsState() in Compose.
 *
 * Log is capped at MAX_LOG_LINES so an overnight session doesn't OOM.
 */
/**
 * User-facing error surfaced via a dialog on the main screen. `title` is the
 * one-line "what went wrong"; `detail` is the secondary explanation / next-step
 * hint (host / port reminder, "update the app", etc.). Driver populates these
 * at each definitive failure point in the handshake/run loop so the user has
 * something to act on instead of "the LED stopped blinking."
 *
 * [actions] are optional extra buttons rendered alongside the default
 * dismiss button. Used (today) to expose a "download APK from this server"
 * jump-out from the proto-version-mismatch error, since the configured
 * Viewer URL is the closest thing to "where this version of the app
 * probably lives."
 */
data class UiError(
    val title: String,
    val detail: String? = null,
    val actions: List<UiErrorAction> = emptyList(),
)

/**
 * Action button rendered next to "OK" on a [UiError] dialog. [OpenUrl]
 * dispatches an ACTION_VIEW intent; the system handler (usually the
 * default browser) takes it from there.
 */
sealed class UiErrorAction {
    abstract val label: String

    /** Hands [url] off to the system via ACTION_VIEW. */
    data class OpenUrl(override val label: String, val url: String) : UiErrorAction()
}

object ConnectionState {
    private const val MAX_LOG_LINES = 500

    private val _logs = MutableStateFlow<List<String>>(emptyList())
    val logs: StateFlow<List<String>> = _logs.asStateFlow()

    private val _serviceRunning = MutableStateFlow(false)
    val serviceRunning: StateFlow<Boolean> = _serviceRunning.asStateFlow()

    private val _connectionActive = MutableStateFlow(false)
    val connectionActive: StateFlow<Boolean> = _connectionActive.asStateFlow()

    /** Server-issued public access key from EncryptedHandshakeServer. Null when not connected. */
    private val _accessKey = MutableStateFlow<String?>(null)
    val accessKey: StateFlow<String?> = _accessKey.asStateFlow()

    /**
     * Hex-encoded inner-e2ee key for this share session. Generated by the
     * service on Server-toggle-on, cleared on disconnect. Stuffed in the URL
     * fragment so the server never sees it - the viewer reads it from
     * `location.hash` and decrypts incoming binary frames locally.
     */
    private val _innerKey = MutableStateFlow<String?>(null)
    val innerKey: StateFlow<String?> = _innerKey.asStateFlow()

    /** True once at least one pong has come back - distinguishes "handshaking" from "fully live". */
    private val _pongReceived = MutableStateFlow(false)
    val pongReceived: StateFlow<Boolean> = _pongReceived.asStateFlow()

    /**
     * Epoch ms (System.currentTimeMillis() scale) when the active share-timer
     * expires. Null when no timer is running. Set by the service when the
     * connection goes "fully live" (first pong) and reset whenever the share-
     * time dial moves. UI computes remaining = value - now.
     */
    private val _shareEndTimeMs = MutableStateFlow<Long?>(null)
    val shareEndTimeMs: StateFlow<Long?> = _shareEndTimeMs.asStateFlow()

    /**
     * Latest server-reported subscriber count, refreshed once per ping cycle.
     * Null when not yet known (e.g. fresh connection, query in flight, or
     * disconnected). The wire value is an unsigned 64-bit integer; the server
     * returns `uint64::MAX` (= -1L signed) as an error sentinel when it can't
     * read the count - the UI surfaces that as "?".
     */
    private val _subCount = MutableStateFlow<Long?>(null)
    val subCount: StateFlow<Long?> = _subCount.asStateFlow()

    /**
     * Last user-actionable connection error. Set by [pl.dubba.share.net.ConnectionDriver]
     * at definitive failure points (proto mismatch, server unreachable, ...),
     * cleared on the next connection start and on user dismiss. UI shows it as
     * a dialog; persisting it across the LED going dark is intentional, so the
     * user gets to see the reason even after the LED has reset.
     */
    private val _lastError = MutableStateFlow<UiError?>(null)
    val lastError: StateFlow<UiError?> = _lastError.asStateFlow()

    /**
     * When true, [appendLog] becomes a no-op (no in-memory append, no disk
     * write). Lets the user stop log churn while alt-tabbing to find parking
     * etc., so the few hundred lines of interest don't rotate away under their
     * feet. UI shows a switch in the Debug screen.
     */
    private val _logsPaused = MutableStateFlow(false)
    val logsPaused: StateFlow<Boolean> = _logsPaused.asStateFlow()

    /**
     * Loads any previously-persisted log lines from disk into the in-memory
     * StateFlow. Idempotent - if logs are already populated (e.g. from a
     * previous call this process), the existing state wins. Call this once
     * during app/service startup, after [DebugLog.init].
     */
    fun bootstrapLogsFromDisk() {
        if (_logs.value.isNotEmpty()) return
        _logs.value = DebugLog.loadAllLines().takeLast(MAX_LOG_LINES)
    }

    fun appendLog(line: String) {
        if (_logsPaused.value) return
        val stamped = "${DebugLog.timestamp()} $line"
        _logs.update { it.plus(stamped).takeLast(MAX_LOG_LINES) }
        DebugLog.append(stamped)
    }

    /**
     * Flip the pause state. The "paused" line is logged BEFORE the flag
     * actually goes on, and the "resumed" line AFTER it comes off, so both
     * bookends always make it into the log. Calls with the same value as
     * current are no-ops.
     */
    fun setLogsPaused(want: Boolean) {
        if (want == _logsPaused.value) return
        if (want) {
            appendLog("⏸ logger paused (manual)")
            _logsPaused.value = true
        } else {
            _logsPaused.value = false
            appendLog("▶ logger resumed (manual)")
        }
    }

    fun clearLogs() {
        _logs.value = emptyList()
        DebugLog.clearAll()
    }

    fun setServiceRunning(running: Boolean) {
        _serviceRunning.value = running
    }

    fun setConnectionActive(active: Boolean) {
        _connectionActive.value = active
        if (active) {
            // Start of a fresh attempt - any stale error from a previous
            // failed session shouldn't haunt this one.
            _lastError.value = null
        } else {
            _accessKey.value = null
            _pongReceived.value = false
            _subCount.value = null
            _innerKey.value = null
            // Note: lastError NOT cleared here. The driver's failure path sets
            // it just before exiting, and setConnectionActive(false) fires
            // right after; clearing here would erase the very thing we just
            // logged. User dismisses the dialog to clear.
        }
    }

    fun setLastError(error: UiError?) {
        _lastError.value = error
    }

    fun setSubCount(count: Long?) {
        _subCount.value = count
    }

    fun setAccessKey(key: String?) {
        _accessKey.value = key
    }

    fun setInnerKey(hex: String?) {
        _innerKey.value = hex
    }

    fun setPongReceived(received: Boolean) {
        _pongReceived.value = received
    }

    fun setShareEndTimeMs(value: Long?) {
        _shareEndTimeMs.value = value
    }
}
